#!/bin/bash

#https://stackoverflow.com/questions/7578930/bash-split-string-into-character-array
# '<CHAR> syntax: https://www.gnu.org/software/coreutils/manual/html_node/printf-invocation.html#printf-invocation
for c in $(echo "$@" | grep -o .); do
    printf '0x%x\n' \'$c
done
